server:
  port: 8082

#数据库日志工具
logging:
  level:
    root: info
    com.aode: debug
#数据库连接信息
spring:
  datasource:
    url: jdbc:mysql://183.237.174.150:25555/new_b2b_shixi?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF8
    #    url: jdbc:mysql://120.79.217.10:3306/sovo_manage?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: shixi
    password: shixi1122
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开启驼峰命名
  mapper-locations: classpath:com/zhongwei/lvzhixuan-manage/mapper/xml/*Mapper.xml
#  type-aliases-package: com.aode.sovomanage.entity